networks:
  metrodelay:
    driver: bridge

services:
  remote-resources:
    image: metro-delay/remote-resources:0.0.1
    container_name: remote-resources
    networks:
      - metrodelay
  metrodelay-ws-rest:
    image: metro-delay/metrodelay-ws-rest:0.0.1
    container_name: metrodelay-ws-rest
    networks:
      - metrodelay