localhost:
  hosts:
    localhost:
  vars:
    cluster: blue
sre-blue:
  hosts:
    grafana-blue:
      ansible_host: 45.77.142.152
      ansible_user: root
blue:
  hosts:
    app-blue:
      ansible_host: 209.250.238.242
      ansible_user: root
  vars:
    cluster: blue