- hosts: localhost
  gather_facts: no
  tasks:  
  - name: list instances
    vultr.cloud.instance_info:
      api_key: "{{ vultr.api_key }}"
      region: "fra"
      label: app
  - name: create instance
    vultr.cloud.instance:
      region: "fra"
      api_key: "{{ vultr.api_key }}"
      backups: false
      hostname: app-{{ cluster }}
      os: Alpine Linux x64
      label: app
      tags:
        - app
        - blue
      plan: vc2-1c-1gb
      ssh_keys:
        - ansible
      user_scheme: root
  - name: list instances
    vultr.cloud.instance_info:
      api_key: "{{ vultr.api_key }}"
      region: "fra"
      label: app