- hosts: localhost
  gather_facts: no
  tasks:  
  - name: list instances
    vultr.cloud.instance_info:
      region: "fra"
      lable: "sre"
      api_key: "{{ vultr.api_key }}"
  - name: create instance
    vultr.cloud.instance:
      region: "fra"
      api_key: "{{ vultr.api_key }}"
      backups: false
      hostname: grafana-{{ cluster }}
      os: Alpine Linux x64
      label: grafana
      tags:
        - sre
        - blue
      plan: vc2-1c-1gb
      ssh_keys:
        - ansible
      user_scheme: root
  - name: list instances
    vultr.cloud.instance_info:
      region: "fra"
      lable: "sre"
      api_key: "{{ vultr.api_key }}"